linters-settings:
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocyclo:
    max-complexity: 20
  gci:
    sections:
      - standard                       # Captures all standard packages if they do not match another section.
      - default                        # Contains all imports that could not be matched to another section type.
      - prefix(github.com/ognick/goscade) # Groups all imports with the specified Prefix.
    custom-order: true
    skip-generated: false
    no-inline-comments: false
    no-prefix-comments: false
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - lll
    - gofmt
    - goimports
    - whitespace
    - gocyclo
    - gci